#!/bin/sh

set -e
workdir=$(pwd $(cd $(dirname $0)))

if [ "lint" == "$1" ] ; then
    python3 -m pip install -q pylint
    python3 -m pylint \
        ${workdir}/scripts/build.py \
        ${workdir}/scripts/python-libs/*
elif [ "ut" == "$1" ] ; then
    python3 -m pip install -q pytest
    python3 -m pytest .
else
    # redirect to build.py
    python3 ${workdir}/scripts/build.py $@
fi


